"""The orchestration graph as code.

`orchestration/graph.yaml` is data; this module is the only thing that
interprets it. Keeping interpretation in one place is what lets the graph stay
authoritative rather than becoming a diagram that drifts from reality.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

GATE_AUTONOMOUS = "autonomous"
GATE_CONFIRM = "confirm"
GATE_HARD_STOP = "hard-stop"

_STATUS_DONE = {"completed", "done"}


@dataclass(frozen=True)
class Node:
    id: str
    title: str
    agent: str
    gate: str
    depends_on: tuple[str, ...]
    budget_tokens: int
    status: str
    spec: str | None
    condition: str | None
    rationale: str | None


@dataclass
class Graph:
    models: dict[str, dict]
    budget: dict
    nodes: dict[str, Node]
    gate_semantics: dict[str, str]

    def model_for(self, node: Node) -> dict:
        """Resolve a node's agent role to a concrete model and effort level."""
        role = self.models.get(node.agent)
        if role is None:
            raise KeyError(
                f"Node {node.id} names agent role {node.agent!r}, "
                f"which is not defined under `models:` in graph.yaml"
            )
        return role

    def unmet_dependencies(self, node: Node) -> list[str]:
        return [
            dep
            for dep in node.depends_on
            if dep not in self.nodes or self.nodes[dep].status not in _STATUS_DONE
        ]

    def runnable(self) -> list[Node]:
        """Nodes whose dependencies are met and which an agent may start now.

        Hard-stop nodes are never runnable by an agent, by construction — a
        filter here rather than a check at the call site, so that forgetting the
        check is not possible.
        """
        return [
            node
            for node in self.nodes.values()
            if node.status not in _STATUS_DONE
            and node.gate != GATE_HARD_STOP
            and not self.unmet_dependencies(node)
        ]

    def validate(self) -> list[str]:
        """Structural problems with the graph. Empty list means healthy."""
        problems: list[str] = []
        for node in self.nodes.values():
            if node.agent not in self.models:
                problems.append(f"{node.id}: unknown agent role {node.agent!r}")
            if node.gate not in self.gate_semantics:
                problems.append(f"{node.id}: unknown gate {node.gate!r}")
            for dep in node.depends_on:
                if dep not in self.nodes:
                    problems.append(f"{node.id}: depends on missing node {dep!r}")
        problems.extend(f"dependency cycle: {' -> '.join(c)}" for c in self._cycles())
        return problems

    def _cycles(self) -> list[list[str]]:
        """Depth-first cycle detection. A cycle here would deadlock the planner."""
        found: list[list[str]] = []
        state: dict[str, int] = {}  # 0 = visiting, 1 = done

        def visit(node_id: str, path: list[str]) -> None:
            if state.get(node_id) == 1:
                return
            if state.get(node_id) == 0:
                found.append(path[path.index(node_id) :] + [node_id])
                return
            state[node_id] = 0
            for dep in self.nodes[node_id].depends_on:
                if dep in self.nodes:
                    visit(dep, path + [node_id])
            state[node_id] = 1

        for node_id in self.nodes:
            visit(node_id, [])
        return found


def load(path: Path) -> Graph:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    nodes: dict[str, Node] = {}
    for entry in raw.get("nodes", []):
        node = Node(
            id=entry["id"],
            title=entry.get("title", ""),
            agent=entry.get("agent", "builder"),
            gate=entry.get("gate", GATE_AUTONOMOUS),
            depends_on=tuple(entry.get("depends_on") or ()),
            budget_tokens=int(entry.get("budget_tokens", 0)),
            status=entry.get("status", "pending"),
            spec=entry.get("spec"),
            condition=entry.get("condition"),
            rationale=entry.get("rationale"),
        )
        nodes[node.id] = node
    return Graph(
        models=raw.get("models", {}),
        budget=raw.get("budget", {}),
        nodes=nodes,
        gate_semantics=raw.get("gate_semantics", {}),
    )


# Gate appearance carries the meaning: a node an agent may not start should not
# look like one it may.
_GATE_STYLE = {
    GATE_AUTONOMOUS: ("", "auto"),
    GATE_CONFIRM: ("", "confirm"),
    GATE_HARD_STOP: ("", "stop"),
}


def to_mermaid(graph: Graph) -> str:
    """Render the graph for humans. Generated — never hand-edit the .mmd."""
    lines = [
        "%% GENERATED by `hwpm govern graph --mermaid`. Edit graph.yaml instead.",
        "flowchart TD",
        "  classDef auto fill:#e8f4f2,stroke:#16777a,color:#12343a;",
        "  classDef confirm fill:#fdf3e0,stroke:#b8791f,color:#4a3208,stroke-width:2px;",
        "  classDef stop fill:#fbe9e9,stroke:#b03636,color:#4a1010,stroke-width:3px;",
        "",
    ]
    for node in graph.nodes.values():
        role = graph.models.get(node.agent, {})
        model = str(role.get("model", "?")).replace("claude-", "").split("-2")[0]
        _, css = _GATE_STYLE.get(node.gate, ("", "auto"))
        label = f"<b>{node.id}</b><br/>{node.title}<br/><i>{node.agent} · {model}</i>"
        lines.append(f'  {node.id}["{label}"]:::{css}')
    lines.append("")
    for node in graph.nodes.values():
        for dep in node.depends_on:
            lines.append(f"  {dep} --> {node.id}")
    return "\n".join(lines) + "\n"
