"""Convert a reference PDF into agent-greppable markdown.

Why this exists as a tool rather than a one-off command: the parsed reference is
an *input* to the optimiser design work, so it has to be reproducible. Anyone
(human or agent) can re-run this and get byte-identical output, which means the
markdown in refs/ never has to be trusted on faith.

Requires the `pdftotext` binary (poppler-utils), which ships with Git for Windows
under /mingw64/bin.

Usage:
    python tools/parse_reference_pdf.py <input.pdf> <output-dir> --slug <slug>
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

# Matches the book's algorithm listings, e.g. "Algorithm 13 Simulated Annealing".
# Trailing marginalia (the author's hand-written asides) are stripped separately.
ALGORITHM_RE = re.compile(r"^Algorithm (\d+)\s+(.*?)\s*$")

# Marginalia are appended to the heading line by pdftotext -layout after a long
# run of spaces. Two-plus spaces is too aggressive (titles contain them after
# column collapse), so require four.
MARGINALIA_RE = re.compile(r"\s{4,}.*$")


@dataclass(frozen=True)
class Algorithm:
    number: int
    title: str
    page: int


def extract_text(pdf: Path, out_txt: Path) -> str:
    """Run pdftotext -layout and return the extracted text.

    -layout is deliberate: the pseudocode listings are whitespace-aligned, and
    the default reading-order mode scrambles them into unusable prose.
    """
    proc = subprocess.run(
        ["pdftotext", "-layout", str(pdf), str(out_txt)],
        capture_output=True,
        text=True,
    )
    # pdftotext warns about missing CJK character collections on this document
    # but still produces complete Latin text, so a non-zero code is not fatal.
    if not out_txt.exists():
        sys.exit(f"pdftotext produced no output.\n{proc.stderr}")
    return out_txt.read_text(encoding="utf-8", errors="replace")


def find_algorithms(pages: list[str]) -> list[Algorithm]:
    found: list[Algorithm] = []
    for page_no, page in enumerate(pages, start=1):
        for line in page.splitlines():
            match = ALGORITHM_RE.match(line)
            if not match:
                continue
            title = MARGINALIA_RE.sub("", match.group(2)).strip()
            # Prose sometimes opens a line with "Algorithm 7. Mutation is ..."
            # -- a cross-reference, not a listing. Real listings are title-cased
            # fragments without sentence punctuation.
            if title.startswith(".") or title.endswith("."):
                continue
            found.append(Algorithm(int(match.group(1)), title, page_no))
    return found


def to_markdown(pages: list[str], slug: str, source_url: str) -> str:
    """Emit page-anchored markdown.

    Page anchors matter more than prettiness here: the consumers are agents doing
    `grep -n` to pull a specific algorithm, and a page anchor lets them cite the
    original PDF page rather than a line number that shifts on every re-parse.
    """
    out: list[str] = [
        f"# {slug}",
        "",
        f"Source: <{source_url}>",
        "",
        "Machine-generated by `tools/parse_reference_pdf.py`. Do not hand-edit;",
        "re-run the tool instead. See `README.md` in this directory for licensing.",
        "",
        "---",
        "",
    ]
    for page_no, page in enumerate(pages, start=1):
        body = page.strip("\n")
        if not body.strip():
            continue
        out.append(f"<!-- page {page_no} -->")
        out.append("")
        out.append(body)
        out.append("")
    return "\n".join(out)


def index_markdown(algorithms: list[Algorithm], slug: str) -> str:
    lines = [
        f"# Algorithm index — {slug}",
        "",
        f"{len(algorithms)} pseudocode listings, generated from the parsed text.",
        "Page numbers refer to the PDF page (1-based), matching the",
        "`<!-- page N -->` anchors in the full-text markdown.",
        "",
        "| # | Algorithm | Page |",
        "|---|-----------|------|",
    ]
    for algo in algorithms:
        lines.append(f"| {algo.number} | {algo.title} | {algo.page} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pdf", type=Path)
    parser.add_argument("out_dir", type=Path)
    parser.add_argument("--slug", required=True)
    parser.add_argument("--source-url", default="")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    raw_txt = args.out_dir / f"{args.slug}.rawtext"

    text = extract_text(args.pdf, raw_txt)
    pages = text.split("\f")
    algorithms = find_algorithms(pages)

    full = args.out_dir / f"{args.slug}.md"
    full.write_text(to_markdown(pages, args.slug, args.source_url), encoding="utf-8")

    index = args.out_dir / "ALGORITHM-INDEX.md"
    index.write_text(index_markdown(algorithms, args.slug), encoding="utf-8")

    raw_txt.unlink()

    print(f"pages={len(pages)} algorithms={len(algorithms)}")
    print(f"wrote {full}")
    print(f"wrote {index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
