/* N14 ward viewer: strategy selector + Pareto front browser + motion overlay.
 * SPEC-005, node N14-viewer.
 *
 * This file holds NO domain logic (SPEC-005 "Artefacts consumed": "the front
 * end must not compute a distance, a total, or an average"). Every number
 * rendered here is read straight off an artefact's `payload`; this file only
 * maps that data onto the design-system primitives (`web/design/index.js`,
 * built at N14a) and onto three.js positions for the ward scene. Coordinate
 * arithmetic (mapping a value to a pixel, or a bed id to a scene position) is
 * rendering, per SPEC-005 decision 9 -- the primitives' scales do the former,
 * `layout.json` does the latter.
 *
 * Data source: `./demo/*.json`, generated by `tools/generate_viewer_artefacts.py`
 * from synthetic/fixture data only (ADR-0005) -- never HWPM_DATA_DIR. Swap
 * `ARTEFACT_BASE` below to point at a different bundle; the shape is fixed by
 * `ArtefactEnvelope` (src/hwpm/artefact/envelope.py) regardless of source.
 */

import * as ds from "./design/index.js";

const ARTEFACT_BASE = "./demo/";

// ---------------------------------------------------------------------------
// Artefact loading
// ---------------------------------------------------------------------------

async function fetchJSON(path) {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return res.json();
}

/** Every strategy's front/motion/opportunities artefact, loaded once and kept
 * in memory -- SPEC-005: "Changing selection is instant (all strategies
 * pre-computed)". Loading all five up front is what makes that true. */
async function loadBundle() {
  const manifest = await fetchJSON(ARTEFACT_BASE + "manifest.json");
  const layout = await fetchJSON(ARTEFACT_BASE + "layout.json");
  const kinds = ["front", "motion", "opportunities", "coverage"];
  const byKind = {};
  for (const kind of kinds) {
    byKind[kind] = {};
    await Promise.all(
      manifest.strategies.map(async (key) => {
        byKind[kind][key] = await fetchJSON(`${ARTEFACT_BASE}${kind}.${key}.json`);
      }),
    );
  }
  return { manifest, layout, ...byKind };
}

// ---------------------------------------------------------------------------
// Ward scene -- built from layout.json, never from a literal WARDS array
// (SPEC-005 acceptance criterion 1).
// ---------------------------------------------------------------------------

function cssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(`--${name}`).trim();
}

class WardScene {
  constructor(stage, THREE, layout) {
    this.stage = stage;
    this.THREE = THREE;
    this.layout = layout;
    this.byId = new Map(layout.nodes.map((n) => [n.id, n]));
    this.group = new THREE.Group();
    this._buildStatic();
    this._buildMarker();
    stage.setObject(this.group);
  }

  _colour(token) {
    return new this.THREE.Color(cssVar(token) || "#888888");
  }

  _buildStatic() {
    const { THREE } = this;
    const bedMat = new THREE.MeshStandardMaterial({ color: this._colour("ink-quiet"), roughness: 0.8 });
    const corridorMat = new THREE.MeshStandardMaterial({ color: this._colour("line-hairline"), roughness: 0.95 });
    const vertMat = new THREE.MeshStandardMaterial({ color: this._colour("accent-quiet"), roughness: 0.6 });
    for (const node of this.layout.nodes) {
      let mesh;
      if (node.kind === "bed") {
        mesh = new THREE.Mesh(new THREE.BoxGeometry(1.0, 0.5, 1.9), bedMat);
        mesh.position.set(node.x, node.y + 0.25, node.z);
      } else if (node.kind === "corridor") {
        mesh = new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.05, 0.6), corridorMat);
        mesh.position.set(node.x, node.y + 0.02, node.z);
      } else {
        mesh = new THREE.Mesh(new THREE.CylinderGeometry(0.5, 0.5, 0.15, 12), vertMat);
        mesh.position.set(node.x, node.y + 0.08, node.z);
      }
      mesh.name = node.id;
      this.group.add(mesh);
    }
    // Edges, drawn quiet -- the routed graph itself, not a schedule.
    const edgeMat = new THREE.LineBasicMaterial({ color: this._colour("line-hairline"), transparent: true, opacity: 0.5 });
    const positions = [];
    for (const edge of this.layout.edges) {
      const a = this.byId.get(edge.a);
      const b = this.byId.get(edge.b);
      if (!a || !b) continue;
      positions.push(a.x, a.y + 0.02, a.z, b.x, b.y + 0.02, b.z);
    }
    const geo = new THREE.BufferGeometry();
    geo.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
    this.group.add(new THREE.LineSegments(geo, edgeMat));
  }

  _buildMarker() {
    const { THREE } = this;
    this.marker = new THREE.Group();
    this.marker.visible = false;
    const body = new THREE.Mesh(
      new THREE.CapsuleGeometry(0.14, 0.42, 6, 12),
      new THREE.MeshStandardMaterial({ color: this._colour("accent"), roughness: 0.5 }),
    );
    body.position.y = 0.35;
    this.marker.add(body);
    this.group.add(this.marker);
    this.trail = new THREE.Mesh(
      new THREE.BufferGeometry(),
      new THREE.MeshBasicMaterial({ color: this._colour("accent"), transparent: true, opacity: 0.6 }),
    );
    this.trail.visible = false;
    this.group.add(this.trail);
  }

  /** Animate `visits` (already ordered) as a route: the marker steps through
   * each visited bed and the trail traces the path walked so far. Motion here
   * explains the schedule's route, which is design bar 4's exception. */
  showRoute(visits) {
    const { THREE } = this;
    const points = visits
      .map((v) => this.byId.get(v.bed))
      .filter(Boolean)
      .map((n) => new THREE.Vector3(n.x, 0.02, n.z));
    if (!points.length) {
      this.marker.visible = false;
      this.trail.visible = false;
      return;
    }
    this.marker.visible = true;
    this.marker.position.copy(points[points.length - 1]).setY(0);
    if (points.length > 1) {
      const curve = new THREE.CatmullRomCurve3(points, false, "catmullrom", 0.1);
      const geo = new THREE.TubeGeometry(curve, Math.max(8, points.length * 6), 0.03, 6, false);
      this.trail.geometry.dispose();
      this.trail.geometry = geo;
      this.trail.visible = true;
    } else {
      this.trail.visible = false;
    }
  }

  clearRoute() {
    this.marker.visible = false;
    this.trail.visible = false;
  }
}

// ---------------------------------------------------------------------------
// Figures
// ---------------------------------------------------------------------------

function provenanceOf(envelope, manifest) {
  return {
    strategy: ds.strategyLabel(envelope.strategy),
    methodVersion: envelope.method_version,
    dateRange: manifest.date_range,
  };
}

function renderMotionFigure(slot, envelope, manifest) {
  const p = envelope.payload;
  const body = document.createElement("div");
  body.className = "stack";
  body.appendChild(
    ds.statistic({
      label: "Observed motion",
      value: p.observed_m.toFixed(0),
      unit: "m",
      exact: true,
      note: `${p.params.n_rounds} rounds over ${p.params.n_ward_days} ward-days`,
    }),
  );
  body.appendChild(
    ds.statistic({
      label: "Attributable to visit ordering (upper bound, perfect foresight)",
      value: p.attributable_m.toFixed(0),
      unit: "m",
      interval: p.ci95.map((v) => v.toFixed(0)),
    }),
  );
  body.appendChild(
    ds.roleLegend(["observed", "necessary", "interval", "baseline"], "Motion encoding"),
  );
  const note = document.createElement("p");
  note.className = "t-micro";
  note.textContent =
    "At most " +
    (100 * p.attributable_fraction).toFixed(1) +
    "% of observed walking was attributable to visit ordering, under perfect " +
    "foresight -- an upper bound on avoidable motion, not a savings estimate.";
  body.appendChild(note);

  const figureNode = ds.figure({
    title: "Motion waste",
    subtitle: "Observed distance against the proven lower-bound necessary tour",
    provenance: provenanceOf(envelope, manifest),
    body,
  });
  slot.replaceChildren(figureNode);
}

function renderOpportunitiesFigure(slot, envelope, manifest) {
  const candidates = envelope.payload.candidates;
  let body;
  if (!candidates.length) {
    body = ds.emptyState(
      "No missed MDT opportunities detected",
      "No clinician's routed path passed near an uninvolved patient who needed their specialty within the proximity and timing window. A real result, not an empty panel.",
    );
  } else {
    const ul = document.createElement("ul");
    ul.className = "opps-list";
    for (const c of candidates.slice(0, 8)) {
      const li = document.createElement("li");
      const head = document.createElement("div");
      head.className = "t-body";
      head.textContent = `${c.clinician} → ${c.patient} (${c.specialty})`;
      const detail = document.createElement("div");
      detail.className = "t-micro";
      detail.textContent = `${c.proximity_m.toFixed(1)} m, confidence ${c.confidence.toFixed(2)} -- ${c.reason}`;
      li.appendChild(head);
      li.appendChild(detail);
      ul.appendChild(li);
    }
    body = ul;
  }
  const figureNode = ds.figure({
    title: "Missed MDT opportunities",
    subtitle: "Candidates only -- never reported as 'missed reviews' (SPEC-002)",
    provenance: provenanceOf(envelope, manifest),
    body,
  });
  slot.replaceChildren(figureNode);
}

function renderGovernanceFigure(slot, envelope, manifest, bundle) {
  const p = envelope.payload;
  const body = document.createElement("div");
  body.className = "stack";

  if (p.withheld) {
    body.appendChild(
      ds.emptyState(
        "MDT coverage withheld",
        p.reason,
      ),
    );
  } else {
    body.appendChild(
      ds.statistic({
        label: "MDT coverage",
        value: (100 * p.coverage).toFixed(1),
        unit: "%",
        interval: p.ci95.map((v) => (100 * v).toFixed(1)),
      }),
    );
    const detail = document.createElement("p");
    detail.className = "t-micro";
    detail.textContent =
      `${p.n_covered} of ${p.n_patients} multi-specialty patients, ` +
      `${p.n_published_cells} ward-day cell(s) published, ` +
      `${p.n_suppressed_cells} withheld under the ADR-0005 floor.`;
    body.appendChild(detail);
  }

  // ADR-0006 point 3: union/intersection are always shown as bounds,
  // regardless of which strategy is selected.
  const boundsKeys = manifest.coverage_bounds_strategies || { upper: "union", lower: "intersection" };
  const boundsWrap = document.createElement("div");
  boundsWrap.className = "stack";
  const boundsLabel = document.createElement("p");
  boundsLabel.className = "t-micro";
  boundsLabel.textContent = "Plausible range across all five RequiredSpecialty strategies:";
  boundsWrap.appendChild(boundsLabel);
  for (const [side, key] of Object.entries(boundsKeys)) {
    const bp = bundle.coverage?.[key]?.payload;
    const line = document.createElement("p");
    line.className = "t-micro";
    if (!bp || bp.withheld) {
      line.textContent = `${side} bound (${key}): withheld -- ${bp ? bp.reason : "not available"}`;
    } else {
      line.textContent =
        `${side} bound (${key}): ${(100 * bp.coverage).toFixed(1)}% ` +
        `[${(100 * bp.ci95[0]).toFixed(1)}%, ${(100 * bp.ci95[1]).toFixed(1)}%]`;
    }
    boundsWrap.appendChild(line);
  }
  body.appendChild(boundsWrap);

  const warning = document.createElement("p");
  warning.className = "t-micro";
  warning.textContent =
    "Measured, never attested (ADR-0006 rule 4). Never quote a bare percentage -- " +
    "the interval and the strategy that produced this denominator travel with the number.";
  body.appendChild(warning);

  const figureNode = ds.figure({
    title: "Clinical Governance — MDT coverage",
    subtitle: "Fraction of multi-specialty patients whose required review happened at the bedside",
    provenance: provenanceOf(envelope, manifest),
    body,
  });
  slot.replaceChildren(figureNode);
}

function renderFrontFigure(slot, envelope, manifest, onSelect) {
  const payload = envelope.payload;
  const wrap = document.createElement("div");
  wrap.className = "stack";
  const { node, highlight } = ds.paretoFront({
    width: 720,
    height: 300,
    objectives: payload.objectives_meta,
    schedules: payload.schedules,
    baseline: payload.baseline,
    onSelect: (id) => onSelect(id === "baseline" ? payload.baseline : payload.schedules.find((s) => s.id === id)),
  });
  wrap.appendChild(node);
  const hint = document.createElement("p");
  hint.className = "t-micro";
  hint.textContent =
    `${payload.schedules.length} schedules shown, unsorted, against today's observed baseline. ` +
    "Arrow keys move between them, Enter selects one into the ward view.";
  wrap.appendChild(hint);
  const figureNode = ds.figure({
    title: "Pareto front — five-objective trade-off",
    subtitle: "No ranking, no recommended schedule (ADR-0004): browse the trade-off yourself",
    provenance: provenanceOf(envelope, manifest),
    body: wrap,
  });
  slot.replaceChildren(figureNode);
  return highlight;
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

async function main() {
  const stageEl = document.createElement("three-d-stage");
  stageEl.id = "stage";
  stageEl.setAttribute("name", "ward-viewer-scene");
  stageEl.setAttribute("background", cssVar("surface-scene") || "#eef1f0");
  const sceneFigureSlot = document.getElementById("scene-figure-slot");
  const sceneBody = document.createElement("div");
  sceneBody.id = "stage-wrap";
  sceneBody.appendChild(stageEl);
  const scheduleReadout = document.createElement("p");
  scheduleReadout.className = "t-micro schedule-readout";
  scheduleReadout.setAttribute("aria-live", "polite");

  let bundle;
  try {
    bundle = await loadBundle();
  } catch (err) {
    const failure = document.createElement("div");
    failure.className = "panel";
    failure.appendChild(
      ds.emptyState(
        "Demo artefacts not found",
        `Run "python tools/generate_viewer_artefacts.py" first, then serve web/ over HTTP ` +
          `(fetch of ./demo/*.json needs a server, not a file:// URL). (${err.message})`,
      ),
    );
    document.getElementById("front-figure-slot").replaceChildren(failure);
    return;
  }

  const { manifest, layout } = bundle;
  let selected = manifest.default_strategy;
  let scene = null;
  let highlightFn = null;

  const sceneWrap = document.createElement("div");
  sceneWrap.className = "stack";
  sceneWrap.appendChild(sceneBody);
  sceneWrap.appendChild(scheduleReadout);
  sceneFigureSlot.replaceChildren(
    ds.figure({
      title: "Ward",
      subtitle: "Bed and corridor positions from layout.json (N06 routed travel graph) -- never hard-coded here",
      provenance: {
        strategy: ds.strategyLabel(selected),
        methodVersion: manifest.method_version,
        dateRange: manifest.date_range,
      },
      body: sceneWrap,
    }),
  );

  await stageEl.ready;
  const THREE = (await import("three"));
  scene = new WardScene(stageEl, THREE, layout);

  function onScheduleSelected(record) {
    if (!record) {
      scene.clearRoute();
      scheduleReadout.textContent = "";
      return;
    }
    scene.showRoute(record.visits ?? []);
    const feasibility = record.feasible === false ? " (infeasible)" : "";
    scheduleReadout.textContent = `Showing ${record.label}${feasibility} in the ward.`;
  }

  function render(strategyKey) {
    selected = strategyKey;
    renderMotionFigure(document.getElementById("motion-figure-slot"), bundle.motion[strategyKey], manifest);
    renderOpportunitiesFigure(
      document.getElementById("opportunities-figure-slot"),
      bundle.opportunities[strategyKey],
      manifest,
    );
    renderGovernanceFigure(
      document.getElementById("governance-figure-slot"),
      bundle.coverage[strategyKey],
      manifest,
      bundle,
    );
    highlightFn = renderFrontFigure(
      document.getElementById("front-figure-slot"),
      bundle.front[strategyKey],
      manifest,
      onScheduleSelected,
    );
    onScheduleSelected(null);
  }

  const legendSlot = document.createElement("div");
  legendSlot.appendChild(ds.strategyLegend(selected));
  document.getElementById("strategy-select-slot").replaceChildren(
    ds.strategySelector({
      selected,
      onSelect: (key) => {
        legendSlot.replaceChildren(ds.strategyLegend(key));
        render(key);
      },
    }),
    legendSlot,
  );

  render(selected);
}

main();
